[build]
  command = "npm run build"   # Build command
  publish = ".next"           # Sets the publish directory to `.next`

[[plugins]]
  package = "@netlify/plugin-nextjs"   # Making sure the Netlify plugin is used