[build]
  command = "pnpm next build --turbo"      # Build command
  # Do not set 'publish' when using '@netlify/plugin-nextjs'

[[plugins]]
  package = "@netlify/plugin-nextjs"   # Making sure the Netlify plugin is used