[build]
  command = "pnpm next build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_CACHE_FOLDER = ".next/cache"

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"